--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/minijaham/UnlimitedSlots
build-by-default: true
branches:
- master
projects:
  UnlimitedSlots:
    path: ""
    icon: meta/infinity.png
...
